ALTER TABLE Users
ALTER COLUMN CreditCard ADD MASKED WITH (FUNCTION = 'partial(0,"XXXX-XXXX-XXXX-" , 4)');

ALTER TABLE Phones
ALTER COLUMN Phone ADD MASKED WITH (FUNCTION = 'default()');

ALTER TABLE Phones
ALTER COLUMN Cell ADD MASKED WITH (FUNCTION = 'partial(0,"XXX-XXX-X",2)');

ALTER TABLE Users
ALTER COLUMN Age ADD MASKED WITH (FUNCTION = 'random(0, 100)');

ALTER TABLE Emails
ALTER COLUMN Email ADD MASKED WITH (FUNCTION = 'email()');

ALTER TABLE Logins
ALTER COLUMN Registerdate ADD MASKED WITH (FUNCTION = 'datetime("Y")');

